### PR TITLE
Set Up Travis CI

### PR DESCRIPTION
**Pull request by CollinDietz**

### CODE REVIEW

**Review by jacobstorms — APPROVED** [review]
lgtm

**Review by jacobstorms — APPROVED** [review]
still lgtm. getting the hang of hitting "approve" rather than "comment". maybe next time i won't even leave one

**Comment by CollinDietz** [comment]
This should be good for a final review, it doesn't run on multiple sims, just the iphone XS. I'll make an issue to extend it.

**Review by TylerLawson — APPROVED** [review]
LGTM

**Pull request merged**
