### PR TITLE
Added python(2.7) script that converts output from generate-data to a…

### PR DESCRIPTION
**Pull request by jacobstorms**
… format Turi Create can use, then trains a CoreML model

### CODE REVIEW

**Comment by jacobstorms** [comment]
This is the script that trained our most recent model. Can't figure out why it fails to merge. Just uploading it for documentation's sake

**Review by TylerLawson — CHANGES_REQUESTED** [review]
Please document your changes more

**Review by TylerLawson — APPROVED** [review]
LGTM

**Comment by jychn** [comment]
LGTM

**Review by jiayijchen — APPROVED** [review]
LGTM

**Pull request merged**
