### PR TITLE
Add 3d labeling capability in ARkit

### PR DESCRIPTION
**Pull request by TylerLawson**
Created 3D model of suit label and added some code to place object in front of camera in AR scene. Mostly testing placement capability and size of blender model object.

### CODE REVIEW

**Comment by jacobstorms** [comment]
Doesn't look like it places anything anywhere. I was under the impression that we'd need a .scn file, too?

**Review by jacobstorms — APPROVED** [review]
LGTM

**Comment by CollinDietz** [comment]
LGTM

**Review by CollinDietz — COMMENTED** [review]
LGTM

**Review by CollinDietz — APPROVED** [review]
My b, its late

**Pull request merged**
